FROM       amazonlinux:2

RUN amazon-linux-extras install epel -y
RUN yum update -y
RUN yum install mc wget nano patch yum-utils deltarpm which rpm-build rpmdevtools git -y
RUN yum groupinstall "Development Tools" -y
COPY ./.rpmmacros.amzn2 /root/.rpmmacros
COPY ./.bashrc /root/.bashrc
